export const API_ENDPOINT = 'https://randomuser.me/api/?results=50'
export const XHR_STATUS_IDLE = 'idle'
export const XHR_STATUS_PENDING = 'pending'
export const XHR_STATUS_REJECTED = 'rejected'
export const XHR_STATUS_FULFILLED = 'fulfilled'